### ISSUE TITLE
Amigo can you update from node16 to node20

### ISSUE THREAD

**Issue by EdwardPrentice** [johnbeynon/render-deploy-action#6]

**Comment by Amigo-The-Developer** [comment]
I've created a pull request addressing this issue
‎
amigo-can-you-update-from-node-16-to-node-20-1722858426666
‎
Updating the Node.js version to node20 in the package.json by specifying it in the "engines" field.
‎
https://github.com/johnbeynon/render-deploy-action/pull/10

**Comment by Amigo-The-Developer** [comment]
I've created a pull request addressing this issue
‎
amigo-can-you-update-from-node-16-to-node-20-1722858438398
‎
Updating the Node.js version suggested in "engines" property to specify Node.js 20.
‎
https://github.com/johnbeynon/render-deploy-action/pull/11
